language: objective-c
osx_image: xcode10
rvm:
  - 2.2.2
cache:
  - bundler

env:
  matrix:
    - RUN_TESTS="YES"
    - BUILD_APP="YES"

before_install:
  - bundle install

script:
  bundle exec fastlane

  - if [ $RUN_TESTS == "YES" ]; then
      fastlane mac test
    fi

  - if [ $BUILD_APP == "YES" ]; then
      fastlane mac build
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)